export enum REPORTS {
     NOT_FINISHED_REPORT = 1,
     CLOSED_ORDERS_REPORT = 2,
     DOWN_PAYMENT_REPORT = 3,
     MONTHLY_REPORT = 4,
     STOCK_YEAR_INVENTORY_REPORT = 5,
     PRODUCTION_YEAR_REPORT = 6,
}
