export const MEASURES_DESCRIPTIONS = [
     // wzrost: { value: '', label: 'wzrost', description: 'wzrost' },
     // obwod_bioder: { value: '', label: 'obwod_bioder', description: 'obwód bioder' },
     // pas_spodni: { value: '', label: 'pas_spodni', description: 'pas spodni' },
     // bark_rekaw: { value: '', label: 'bark_rekaw', description: 'bark/rękaw' },
     // szerokosc_przodu: { value: '', label: 'szerokość_przodu', description: 'szerokość przodu' },
     // obwod_klatki_piersiowej: {
     //      value: '',
     //      label: 'obwod_klatki_piersiowej',
     //      description: 'obwód klatki piersiowej',
     // },
     // obwod_pasa_marynarki: { value: '', label: 'obwod_pasa_marynarki', description: "obwód pasa marynarki'" },
     // szerokosc_tylu: { value: '', label: 'szerokosc_tylu', description: 'szerokość tyłu' },
     // obwod_uda: { value: '', label: 'obwod_uda', description: 'obwód uda' },
     // szerokosc_barkow: { value: '', label: 'szerokosc_barkow', description: "szerokość barków'" },
     // długosc_plecow: { value: '', label: 'długosc_plecow', description: 'długość pleców' },
     // obwod_bicepsu: { value: '', label: 'obwod_bicepsu', description: 'obwód bicepsu' },
     // dl_zewn_nogawki_bez_paska: {
     //      value: '',
     //      label: 'dl_zewn_nogawki_bez_paska',
     //      description: "dł.zewn.nogawki bez paska'",
     // },
     // uwagi: { value: '', label: 'uwagi', description: 'uwagi' },
// };
{ "value": "", "label": "obwod_klatki_piersiowej", "description": "obwód klatki piersiowej" },
{ "value": "", "label": "obwod_pasa_marynarki", "description": "obwód pasa marynarki'" },
{ "value": "", "label": "pas_spodni", "description": "pas spodni" },
{ "value": "", "label": "wzrost", "description": "wzrost" },
// { "value": "", "label": "szerokość_przodu", "description": "szerokość przodu" },
// { "value": "", "label": "szerokosc_tylu", "description": "szerokość tyłu" },
// { "value": "", "label": "bark_rekaw", "description": "bark/rękaw" },
// { "value": "", "label": "obwod_uda", "description": "obwód uda" },
// { "value": "", "label": "szerokosc_barkow", "description": "szerokość barków'" },
// { "value": "", "label": "długosc_plecow", "description": "długość pleców" },
// { "value": "", "label": "obwod_bicepsu", "description": "obwód bicepsu" },
// { "value": "", "label": "obwod_bioder", "description": "obwód bioder" },
// { "value": "", "label": "dl_zewn_nogawki_bez_paska", "description": "dł.zewn.nogawki bez paska'" },
// { "value": "", "label": "uwagi", "description": "uwagi" }
];
